version: "3.9"

services:
  postgres:
    image: postgres:15  # Используем образ PostgreSQL версии 15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"  # Пробрасываем порт из .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранилище для данных


volumes:
  postgres_data:  # Определяем volume для хранения данных

