version: "3.8"
services:
  postgres:
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  etl:
    build: .
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env
